/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b40e17c65024e50ef43b2d87c9964f4f)
interface __BaseEnv_Env {
	DB: D1Database;
	WRITE_RATE_LIMITER: RateLimit;
	READ_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
