/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 64242b5b22e8722e8feb4a9d4f0908bc)
interface __BaseEnv_Env {
	DB: D1Database;
	REGISTRATION_RATE_LIMITER: RateLimit;
	WRITE_RATE_LIMITER: RateLimit;
	READ_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
