/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 977d7fca12f44c61d02321ce3f3a3840)
interface __BaseEnv_Env {
	DB: D1Database;
	WRITE_RATE_LIMITER: RateLimit;
	READ_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
